#include "onnx_runner.h"
#include <iostream>
#include <stdexcept>
#include <string>

ONNXRunner::ONNXRunner(const std::string& model_path)
    : env(ORT_LOGGING_LEVEL_WARNING, "ONNXRunner"),
      memory_info(Ort::MemoryInfo::CreateCpu(OrtArenaAllocator, OrtMemTypeDefault)) {
    
    Ort::SessionOptions session_options;
    session_options.SetIntraOpNumThreads(1);
    
    // Convert string path to wstring for Windows
    std::wstring w_model_path = std::wstring(model_path.begin(), model_path.end());
    
    try {
        session = Ort::Session(env, w_model_path.c_str(), session_options);
    } catch (const Ort::Exception& e) {
        std::cerr << "Failed to load ONNX model: " << e.what() << std::endl;
        throw;
    }

    // Set static names based on our python export format
    input_node_names = {"input"};
    output_node_names = {"output"};
}

ONNXRunner::~ONNXRunner() {
}

std::vector<float> ONNXRunner::predict(const std::vector<float>& input_data, int batch_size, int seq_len, int n_features) {
    if (input_data.size() != batch_size * seq_len * n_features) {
        throw std::invalid_argument("Input data size does not match expected dimensions.");
    }

    std::vector<int64_t> input_node_dims = {batch_size, seq_len, n_features};
    
    auto input_tensor = Ort::Value::CreateTensor<float>(
        memory_info,
        const_cast<float*>(input_data.data()),
        input_data.size(),
        input_node_dims.data(),
        input_node_dims.size()
    );

    auto output_tensors = session.Run(
        Ort::RunOptions{nullptr},
        input_node_names.data(),
        &input_tensor,
        1,
        output_node_names.data(),
        1
    );

    if (output_tensors.empty()) {
        throw std::runtime_error("No output generated by the ONNX model.");
    }

    float* floatarr = output_tensors.front().GetTensorMutableData<float>();
    size_t count = output_tensors.front().GetTensorTypeAndShapeInfo().GetElementCount();

    return std::vector<float>(floatarr, floatarr + count);
}
