"""
features/engineering — public sub-package for feature construction.

Symbols are sourced from the split modules within this package.
"""

from .core import (
    FeatureEngineer,
    sanitize_frame,
    _SANITIZE_NO_CLIP,
    _DEFAULT_PIT_DELAY_MINUTES,
    _with_available_time,
    _join_asof_available,
)
from .cross_asset import CrossAssetFeatures
from .regime_gate import RegimeGateClassifier
from .microstructure import (
    order_flow_imbalance,
    order_book_imbalance_proxy,
    trade_arrival_rate,
    kyles_lambda,
    amihud_illiquidity,
    multi_level_obi,
    vpin,
    realized_spread,
    order_book_imbalance_l2,
    embedding_placeholders,
    compute_finbert_embeddings,
    frac_diff_proxy,
    average_true_range,
    rolling_volatility,
    bollinger_bands,
    rsi,
    macd,
    lag_returns,
    stochastic_oscillator,
    williams_r,
    cci,
    candle_body,
    candle_range,
    upper_shadow,
    lower_shadow,
    is_doji,
    is_hammer,
    is_shooting_star,
    is_engulfing,
    is_harami,
    is_morning_star,
    is_evening_star,
    is_three_white_soldiers,
    is_three_black_crows,
    all_candlestick_patterns,
    vwap_bands,
    volume_weighted_momentum,
    add_volume_profile_features,
    add_volatility_clock_features,
    multi_scale_atr,
    multi_scale_vol,
    ofi_surprise,
    breakout_pressure,
    liquidity_vacuum,
    vol_of_vol,
    price_ofi_divergence,
    vol_filter,
    _pip_size_for_pair,
    add_spread_cost_features,
    add_market_regime_features,
    add_higher_timeframe_context,
    missingness_flags,
    compute_latency_feature,
    circuit_breaker_features,
    position_limit_flags,
    feature_discovery_mutual_info,
    onnx_compatible_features,
    quantize_aware_features,
    model_card_template,
    population_based_hpo_config,
)
from .regime import (
    hmm_regime_probs,
    cpd_ret,
    regime_persistence,
    regime_gated_features,
    interaction_features,
    compute_quality_report,
)
from .macro import (
    carry_features,
    yield_curve_slope,
    correlation_breakdown,
)
from .sentiment import (
    sentiment_decay,
    buzz_score,
    proj_finbert,
    sentiment_tiers,
    news_filter_expr,
)
from .session import (
    tod_sin_cos,
    dow_sin_cos,
    london_ny_session,
)

__all__ = [
    # Core public API
    "FeatureEngineer",
    "sanitize_frame",
    "CrossAssetFeatures",
    "RegimeGateClassifier",
    # PIT join helpers
    "_SANITIZE_NO_CLIP",
    "_DEFAULT_PIT_DELAY_MINUTES",
    "_with_available_time",
    "_join_asof_available",
    # Microstructure
    "order_flow_imbalance",
    "order_book_imbalance_proxy",
    "trade_arrival_rate",
    "kyles_lambda",
    "amihud_illiquidity",
    "multi_level_obi",
    "vpin",
    "realized_spread",
    "order_book_imbalance_l2",
    "embedding_placeholders",
    "compute_finbert_embeddings",
    "frac_diff_proxy",
    "average_true_range",
    "rolling_volatility",
    "bollinger_bands",
    "rsi",
    "macd",
    "lag_returns",
    "stochastic_oscillator",
    "williams_r",
    "cci",
    "all_candlestick_patterns",
    "vwap_bands",
    "volume_weighted_momentum",
    "add_volume_profile_features",
    "add_volatility_clock_features",
    "multi_scale_atr",
    "multi_scale_vol",
    "ofi_surprise",
    "breakout_pressure",
    "liquidity_vacuum",
    "vol_of_vol",
    "price_ofi_divergence",
    "vol_filter",
    "add_spread_cost_features",
    "add_market_regime_features",
    "add_higher_timeframe_context",
    "missingness_flags",
    "compute_latency_feature",
    "circuit_breaker_features",
    "position_limit_flags",
    # Regime
    "hmm_regime_probs",
    "cpd_ret",
    "regime_persistence",
    "regime_gated_features",
    "interaction_features",
    "compute_quality_report",
    # Macro
    "carry_features",
    "yield_curve_slope",
    "correlation_breakdown",
    # Sentiment
    "sentiment_decay",
    "buzz_score",
    "proj_finbert",
    "sentiment_tiers",
    "news_filter_expr",
    # Session
    "tod_sin_cos",
    "dow_sin_cos",
    "london_ny_session",
    # Governance/utils
    "onnx_compatible_features",
    "quantize_aware_features",
    "model_card_template",
    "population_based_hpo_config",
    "feature_discovery_mutual_info",
]
